import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HASH BUSINESS RUN 1.0",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        
        <Navbar/>
        {children}
        
        
        
        </body>
    </html>
  );
}
